version: '3'

services:
  app:
    build:
      context: .
    container_name: bluetooth-proximity-sensor
    restart: always
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ./config.yaml:/app/config.yaml
    network_mode: host
